ToonYou:
  base: ""
  path: "./checkpoints/base_models/toonyou_beta3.safetensors"
  inference_config: "configs/inference/inference-v2.yaml"

  seed:           [42]
  steps:          25
  guidance_scale: 7.5

  prompt:
    - "anime, a girl with red hair and blue eyes stands in a garden, dnd avatar portrait of halfling, artgerm and atey ghailan, ios icon, style of disney animation, streaming, jazza and rossdraws, summer afternoon, beautiful and realistic faces, manga styling, animated disney movie inking, anna"
    - "a close up of a woman holding a firework in her hand, girls frontline cg, toga, animated, thancred waters in style of wlop, stylized portrait h 1280, kanliu666, disco elysium, beautiful crying! android woman, streaming, 2d icon, chinese fantasy, manga, lava, profile picture 1024px"
    # - "best quality, masterpiece, 1girl, looking at viewer, blurry background, upper body, contemporary, dress"
    # - "masterpiece, best quality, 1girl, solo, cherry blossoms, hanami, pink flower, white flower, spring season, wisteria, petals, flower, plum blossoms, outdoors, falling petals, white hair, black eyes,"
    # - "best quality, masterpiece, 1boy, formal, abstract, looking at viewer, masculine, marble pattern"
    # - "best quality, masterpiece, 1girl, cloudy sky, dandelion, contrapposto, alternate hairstyle,"

  n_prompt:
    - "forges, breaking bad, man ray 1 9 9 0, anders petersen, dark fog surrounds him, interior photograph, william s burroughs, front elevation, giger ), 2 0 0 4 photograph, memphis abstract minimal art, trent parke, floor plan, david rudnick"
    - "ron mueck, patrick bateman), 1950s press photo, z. beksinski, conde nast traveler photo, john caple, andrei tarkovski"
    # - ""
    # - ""

  
  init_image:
    - "./init_images/t1.jpeg"
    - "./init_images/init.jpg"

