RealisticVision:
  base: ""
  path: "models/DreamBooth_LoRA/realisticVisionV20_v20.safetensors"
  # path: "models/DreamBooth_LoRA/toonyou_beta3.safetensors"

  inference_config: "configs/inference/inference-v2.yaml"
  motion_module:
    - "models/Motion_Module/mm_sd_v15_v2.ckpt"

  # seed:           [13100322578370451493, 14752961627088720670, 9329399085567825781, 16987697414827649302]
  seed:           [42]
  steps:          25
  guidance_scale: 7.5

  prompt:
    # - "beach, large rocks, waves, cloudy sky, dark clouds, flowing water"
    # - "masterpiece, best quality, young man, blue eyes, ((crying)), pain, sadness, red lipstick, puffy eyes, black turtleneck sweater, ripped jeans, dark background, light sources, sadness, despair"
    # - "best quality, masterpiece, mountains, trees, fog, flowing cloudy, peaceful, serene"
    # - "photo of People, walking, sidewalk, building, casual clothing, bags, umbrellas, strollers, sky, trees, buildings"
    # - "photo of lake, mountains, trees, stars, milky way, night sky, serenity, tranquility, wonder, awe."
    # - "photo of herd, elk, grazing, grassy meadow, mountains, overcast, fog, line, rugged, rocky, snow, ice, peaks"
    # - "blue, abstract sculpture, metal rods, spiral shape, movement, energy, calmness, tranquility"
    # - "best quality, masterpiece, polar bear, rocky surface, blue sky, fluffy clouds, cute expression, nap, peaceful, serene"
    # - "best quality, masterpiece, elderly man, walking stick, plaid shirt, hat, beard, mustache, foggy background, trees in the distance"
    # - "best quality, masterpiece, Carnival, Amusement park, Night, Rides, Ferris wheel, Roller coaster, Merry go round, Neon lights, Excitement, Fun"

    - "there is a large body of water that is near a rocky shore, sony a7r -, pinhole, stormy setting, joongwon jeong, 5 2 mm f 5. 6, elaborated depth of field, hdr smooth, water swirling, sony a 7 siii, photo 1 5 mm, wet clay"
    - "masterpiece, best quality, young man, blue eyes, ((crying)), pain, sadness, red lipstick, puffy eyes, black turtleneck sweater, ripped jeans, dark background, light sources, sadness, despair"
    - "best quality, masterpiece, mountains, trees, fog, flowing cloudy, peaceful, serene"
    - "photo of People, walking, sidewalk, building, casual clothing, bags, umbrellas, strollers, sky, trees, buildings"
    - "photo of lake, mountains, trees, stars, milky way, night sky, serenity, tranquility, wonder, awe."
    - "photo of herd, elk, grazing, grassy meadow, mountains, overcast, fog, line, rugged, rocky, snow, ice, peaks"
    - "blue, abstract sculpture, metal rods, spiral shape, movement, energy, calmness, tranquility"
    - "best quality, masterpiece, polar bear, rocky surface, blue sky, fluffy clouds, cute expression, nap, peaceful, serene"
    - "best quality, masterpiece, elderly man, walking stick, plaid shirt, hat, beard, mustache, foggy background, trees in the distance"
    - "best quality, masterpiece, Carnival, Amusement park, Night, Rides, Ferris wheel, Roller coaster, Merry go round, Neon lights, Excitement, Fun"


  n_prompt:
    - "j. c. leyendecker. black hair, cute rave outfit, philippe caza, gouache on paper, 1 9 4 0 s street scene, inside a space station, red square moscow, catherine nolin, 1987 pulp art, micron pen drawing, gouache and ink, kalighat, colored paper collage, artgerm and ilya kuvshinov"
    - ""
    - ""
    - ""
    - ""
    - ""
    - ""
    - ""
    - ""
    - ""

    # - "blur, haze, deformed iris, deformed pupils, semi-realistic, cgi, 3d, render, sketch, cartoon, drawing, anime, mutated hands and fingers, deformed, distorted, disfigured, poorly drawn, bad anatomy, wrong anatomy, extra limb, missing limb, floating limbs, disconnected limbs, mutation, mutated, ugly, disgusting, amputation"
    #- "semi-realistic, cgi, 3d, render, sketch, cartoon, drawing, anime, text, close up, cropped, out of frame, worst quality, low quality, jpeg artifacts, ugly, duplicate, morbid, mutilated, extra fingers, mutated hands, poorly drawn hands, poorly drawn face, mutation, deformed, blurry, dehydrated, bad anatomy, bad proportions, extra limbs, cloned face, disfigured, gross proportions, malformed limbs, missing arms, missing legs, extra arms, extra legs, fused fingers, too many fingers, long neck"
    # - "semi-realistic, cgi, 3d, render, sketch, cartoon, drawing, anime, text, close up, cropped, out of frame, worst quality, low quality, jpeg artifacts, ugly, duplicate, morbid, mutilated, extra fingers, mutated hands, poorly drawn hands, poorly drawn face, mutation, deformed, blurry, dehydrated, bad anatomy, bad proportions, extra limbs, cloned face, disfigured, gross proportions, malformed limbs, missing arms, missing legs, extra arms, extra legs, fused fingers, too many fingers, long neck"
    # - "blur, haze, deformed iris, deformed pupils, semi-realistic, cgi, 3d, render, sketch, cartoon, drawing, anime, mutated hands and fingers, deformed, distorted, disfigured, poorly drawn, bad anatomy, wrong anatomy, extra limb, missing limb, floating limbs, disconnected limbs, mutation, mutated, ugly, disgusting, amputation"
    # - "blur, haze, deformed iris, deformed pupils, semi-realistic, cgi, 3d, render, sketch, cartoon, drawing, anime, art, mutated hands and fingers, deformed, distorted, disfigured, poorly drawn, bad anatomy, wrong anatomy, extra limb, missing limb, floating limbs, disconnected limbs, mutation, mutated, ugly, disgusting, amputation"
  
  init_image:
    - "/root/lh/AnimateDiffcontrolnet-main/init_images/00.jpg"
    - "/root/lh/AnimateDiffcontrolnet-main/init_images/11.jpg"
    - "/root/lh/AnimateDiffcontrolnet-main/init_images/22.jpg"
    - "/root/lh/AnimateDiffcontrolnet-main/init_images/33.jpg"
    - "/root/lh/AnimateDiffcontrolnet-main/init_images/44.jpg"
    - "/root/lh/AnimateDiffcontrolnet-main/init_images/55.jpg"
    - "/root/lh/AnimateDiffcontrolnet-main/init_images/66.jpg"
    - "/root/lh/AnimateDiffcontrolnet-main/init_images/77.jpg"
    - "/root/lh/AnimateDiffcontrolnet-main/init_images/88.jpg"
    - "/root/lh/AnimateDiffcontrolnet-main/init_images/99.jpg"


  # prompt:
  #   - "b&w photo of 42 y.o man in black clothes, bald, face, half body, body, high detailed skin, skin pores, coastline, overcast weather, wind, waves, 8k uhd, dslr, soft lighting, high quality, film grain, Fujifilm XT3"
  #   - "close up photo of a rabbit, forest, haze, halation, bloom, dramatic atmosphere, centred, rule of thirds, 200mm 1.4f macro shot"
  #   - "photo of coastline, rocks, storm weather, wind, waves, lightning, 8k uhd, dslr, soft lighting, high quality, film grain, Fujifilm XT3"
  #   - "night, b&w photo of old house, post apocalypse, forest, storm weather, wind, rocks, 8k uhd, dslr, soft lighting, high quality, film grain"

  # n_prompt:
  #   - "semi-realistic, cgi, 3d, render, sketch, cartoon, drawing, anime, text, close up, cropped, out of frame, worst quality, low quality, jpeg artifacts, ugly, duplicate, morbid, mutilated, extra fingers, mutated hands, poorly drawn hands, poorly drawn face, mutation, deformed, blurry, dehydrated, bad anatomy, bad proportions, extra limbs, cloned face, disfigured, gross proportions, malformed limbs, missing arms, missing legs, extra arms, extra legs, fused fingers, too many fingers, long neck"
  #   - "semi-realistic, cgi, 3d, render, sketch, cartoon, drawing, anime, text, close up, cropped, out of frame, worst quality, low quality, jpeg artifacts, ugly, duplicate, morbid, mutilated, extra fingers, mutated hands, poorly drawn hands, poorly drawn face, mutation, deformed, blurry, dehydrated, bad anatomy, bad proportions, extra limbs, cloned face, disfigured, gross proportions, malformed limbs, missing arms, missing legs, extra arms, extra legs, fused fingers, too many fingers, long neck"
  #   - "blur, haze, deformed iris, deformed pupils, semi-realistic, cgi, 3d, render, sketch, cartoon, drawing, anime, mutated hands and fingers, deformed, distorted, disfigured, poorly drawn, bad anatomy, wrong anatomy, extra limb, missing limb, floating limbs, disconnected limbs, mutation, mutated, ugly, disgusting, amputation"
  #   - "blur, haze, deformed iris, deformed pupils, semi-realistic, cgi, 3d, render, sketch, cartoon, drawing, anime, art, mutated hands and fingers, deformed, distorted, disfigured, poorly drawn, bad anatomy, wrong anatomy, extra limb, missing limb, floating limbs, disconnected limbs, mutation, mutated, ugly, disgusting, amputation"
